//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportBetting.WPF.Prism.Shared.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/01/2013 00:00:00")]
        public global::System.DateTime DA2_DRIVER_INF_MODIFIED {
            get {
                return ((global::System.DateTime)(this["DA2_DRIVER_INF_MODIFIED"]));
            }
            set {
                this["DA2_DRIVER_INF_MODIFIED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/01/2013 00:00:00")]
        public global::System.DateTime DA2_DRIVER_DATE_MODIFIED {
            get {
                return ((global::System.DateTime)(this["DA2_DRIVER_DATE_MODIFIED"]));
            }
            set {
                this["DA2_DRIVER_DATE_MODIFIED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DA2_DRIVER_VERSION {
            get {
                return ((string)(this["DA2_DRIVER_VERSION"]));
            }
            set {
                this["DA2_DRIVER_VERSION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/01/2013 00:00:00")]
        public global::System.DateTime ID_READER_DRIVER_INF_MODIFIED {
            get {
                return ((global::System.DateTime)(this["ID_READER_DRIVER_INF_MODIFIED"]));
            }
            set {
                this["ID_READER_DRIVER_INF_MODIFIED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/01/2013 00:00:00")]
        public global::System.DateTime ID_READER_DRIVER_DATE_MODIFIED {
            get {
                return ((global::System.DateTime)(this["ID_READER_DRIVER_DATE_MODIFIED"]));
            }
            set {
                this["ID_READER_DRIVER_DATE_MODIFIED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ID_READER_DRIVER_VERSION {
            get {
                return ((string)(this["ID_READER_DRIVER_VERSION"]));
            }
            set {
                this["ID_READER_DRIVER_VERSION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/01/2013 00:00:00")]
        public global::System.DateTime TOUCH_SCREEN_DRIVER_INF_MODIFIED {
            get {
                return ((global::System.DateTime)(this["TOUCH_SCREEN_DRIVER_INF_MODIFIED"]));
            }
            set {
                this["TOUCH_SCREEN_DRIVER_INF_MODIFIED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/01/2013 00:00:00")]
        public global::System.DateTime TOUCH_SCREEN_DRIVER_DATE_MODIFIED {
            get {
                return ((global::System.DateTime)(this["TOUCH_SCREEN_DRIVER_DATE_MODIFIED"]));
            }
            set {
                this["TOUCH_SCREEN_DRIVER_DATE_MODIFIED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TOUCH_SCREEN_DRIVER_VERSION {
            get {
                return ((string)(this["TOUCH_SCREEN_DRIVER_VERSION"]));
            }
            set {
                this["TOUCH_SCREEN_DRIVER_VERSION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/01/2013 00:00:00")]
        public global::System.DateTime PRINTER_DRIVER_INF_MODIFIED {
            get {
                return ((global::System.DateTime)(this["PRINTER_DRIVER_INF_MODIFIED"]));
            }
            set {
                this["PRINTER_DRIVER_INF_MODIFIED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/01/2013 00:00:00")]
        public global::System.DateTime PRINTER_DRIVER_DATE_MODIFIED {
            get {
                return ((global::System.DateTime)(this["PRINTER_DRIVER_DATE_MODIFIED"]));
            }
            set {
                this["PRINTER_DRIVER_DATE_MODIFIED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PRINTER_DRIVER_VERSION {
            get {
                return ((string)(this["PRINTER_DRIVER_VERSION"]));
            }
            set {
                this["PRINTER_DRIVER_VERSION"] = value;
            }
        }
    }
}
