//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportBetting.WPF.Prism.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SportBetting.WPF.Prism.Shared.Resources.LogMessages", typeof(LogMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breite der Terminal-Live-Wett-Anzeige zu klein: {0}.
        /// </summary>
        internal static string BetDisplayxaml1 {
            get {
                return ResourceManager.GetString("BetDisplayxaml1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Höhe der Terminal-Live-Wett-Anzeige zu klein: {0}.
        /// </summary>
        internal static string BetDisplayxaml2 {
            get {
                return ResourceManager.GetString("BetDisplayxaml2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving tickets two times.
        /// </summary>
        internal static string ButtonActions2 {
            get {
                return ResourceManager.GetString("ButtonActions2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucessfully printed Credit note with stake {0}EUR.
        /// </summary>
        internal static string ButtonActions3 {
            get {
                return ResourceManager.GetString("ButtonActions3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to print Credit note with stake {0}EUR.
        /// </summary>
        internal static string ButtonActions4 {
            get {
                return ResourceManager.GetString("ButtonActions4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbekannte Antwort auf SaveTicket(): {0}.
        /// </summary>
        internal static string ButtonActions5 {
            get {
                return ResourceManager.GetString("ButtonActions5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ende der Sync-Station-Settings-Schleife erreicht.
        /// </summary>
        internal static string DataSynchronizer1 {
            get {
                return ResourceManager.GetString("DataSynchronizer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ende der Sync-Database-Schleife erreicht.
        /// </summary>
        internal static string DataSynchronizer2 {
            get {
                return ResourceManager.GetString("DataSynchronizer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ende der Export-Database-Schleife erreicht.
        /// </summary>
        internal static string DataSynchronizer3 {
            get {
                return ResourceManager.GetString("DataSynchronizer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ende der Cleanup-Database-Schleife erreicht.
        /// </summary>
        internal static string DataSynchronizer4 {
            get {
                return ResourceManager.GetString("DataSynchronizer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport-DB-Sync wird fortgesetzt.
        /// </summary>
        internal static string DataSynchronizer8 {
            get {
                return ResourceManager.GetString("DataSynchronizer8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station restarted because it was unable to load new version.
        /// </summary>
        internal static string DataSynchronizer9 {
            get {
                return ResourceManager.GetString("DataSynchronizer9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to match is null in DbQueries.GetBetDomains.
        /// </summary>
        internal static string DBQueries1 {
            get {
                return ResourceManager.GetString("DBQueries1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn es keine Sport-Wetten gibt, sollte dann der LastMinuteMatch-Button nicht deaktiviert sein?.
        /// </summary>
        internal static string DBQueries5 {
            get {
                return ResourceManager.GetString("DBQueries5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP DB-Upload fehlgeschlagen..
        /// </summary>
        internal static string ExportDatabase1 {
            get {
                return ResourceManager.GetString("ExportDatabase1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ungültige Live-Info-Fenster-Größe von {0}x{1} auf Fenster {2}.
        /// </summary>
        internal static string InfoDisplayxaml1 {
            get {
                return ResourceManager.GetString("InfoDisplayxaml1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket-Duplikat wurde gedruckt.
        /// </summary>
        internal static string KeyMenuWindowxaml1 {
            get {
                return ResourceManager.GetString("KeyMenuWindowxaml1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket-Duplikat konnte nicht gedruckt werden.
        /// </summary>
        internal static string KeyMenuWindowxaml2 {
            get {
                return ResourceManager.GetString("KeyMenuWindowxaml2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combi Limits not set in Table CombiLimit.
        /// </summary>
        internal static string LimitHandling1 {
            get {
                return ResourceManager.GetString("LimitHandling1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combi Limits not set in Table CombiLimit.
        /// </summary>
        internal static string LimitHandling2 {
            get {
                return ResourceManager.GetString("LimitHandling2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbindung zum LiveBet-Server beendet.
        /// </summary>
        internal static string LiveBetClient1 {
            get {
                return ResourceManager.GetString("LiveBetClient1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import failed.
        /// </summary>
        internal static string LiveBetClient2 {
            get {
                return ResourceManager.GetString("LiveBetClient2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbindung zum LiveBetServer abgebrochen. Es wurde {0} versucht eine Nachricht vom Server zu lesen..
        /// </summary>
        internal static string LiveBetClient3 {
            get {
                return ResourceManager.GetString("LiveBetClient3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client hat Verbindung zum LiveBet-Server {0} am Port {1} verloren. wegen null-message.
        /// </summary>
        internal static string LiveBetClient4 {
            get {
                return ResourceManager.GetString("LiveBetClient4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown LB_PeriodInfo on Terminal {0}: {1}.
        /// </summary>
        internal static string OddButton1 {
            get {
                return ResourceManager.GetString("OddButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active BetDomain in BetStop found .
        /// </summary>
        internal static string OddButton2 {
            get {
                return ResourceManager.GetString("OddButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown LB_PeriodInfo on Terminal {0}: {1}.
        /// </summary>
        internal static string OddDisplayItem1 {
            get {
                return ResourceManager.GetString("OddDisplayItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active BetDomain in BetStop found .
        /// </summary>
        internal static string OddDisplayItem2 {
            get {
                return ResourceManager.GetString("OddDisplayItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Anzeigen der Live-Matches auf Bildschirm {0}: {1}.
        /// </summary>
        internal static string OutletMainView1 {
            get {
                return ResourceManager.GetString("OutletMainView1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESC/POS-Drucker nicht gefunden: {0}.
        /// </summary>
        internal static string PrinterHandler1 {
            get {
                return ResourceManager.GetString("PrinterHandler1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESC/POS-Drucker hat kein Papier: {0}.
        /// </summary>
        internal static string PrinterHandler2 {
            get {
                return ResourceManager.GetString("PrinterHandler2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows-Standard-Drucker nicht verfügbar: {0}.
        /// </summary>
        internal static string PrinterHandler3 {
            get {
                return ResourceManager.GetString("PrinterHandler3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Drucker-Test vom Typ: {0}: {1}.
        /// </summary>
        internal static string PrinterHandler4 {
            get {
                return ResourceManager.GetString("PrinterHandler4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Verbindung zu Netzwerkdrucker.
        /// </summary>
        internal static string PrinterHandler5 {
            get {
                return ResourceManager.GetString("PrinterHandler5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbekannte Auflösung {0}*{1}.
        /// </summary>
        internal static string Resolution1 {
            get {
                return ResourceManager.GetString("Resolution1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong resolution:{0}x{1}.
        /// </summary>
        internal static string Sportwettenxaml1 {
            get {
                return ResourceManager.GetString("Sportwettenxaml1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastViewIdleTime nicht gesetzt.
        /// </summary>
        internal static string StationDataHandler1 {
            get {
                return ResourceManager.GetString("StationDataHandler1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station erfolgreich beendet.
        /// </summary>
        internal static string StationForker1 {
            get {
                return ResourceManager.GetString("StationForker1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station abgestürzt {0}.
        /// </summary>
        internal static string StationForker2 {
            get {
                return ResourceManager.GetString("StationForker2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler im Pref-File. Station gesperrt.
        /// </summary>
        internal static string StationSettings1 {
            get {
                return ResourceManager.GetString("StationSettings1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kein Drucker vorhanden: Erstellung fehlgeschlagen.
        /// </summary>
        internal static string StationSettings10 {
            get {
                return ResourceManager.GetString("StationSettings10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültiger Drucker-Port: {0} Erstellung fehlgeschlagen.
        /// </summary>
        internal static string StationSettings11 {
            get {
                return ResourceManager.GetString("StationSettings11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSP100USB-Verzeichnis hat zu wenige Dateien ({0}) Keine Drucker-Tests auf dieser Station.
        /// </summary>
        internal static string StationSettings12 {
            get {
                return ResourceManager.GetString("StationSettings12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSP100LAN-Verzeichnis hat zu wenige Dateien ({0}) Keine Drucker-Tests auf dieser Station.
        /// </summary>
        internal static string StationSettings13 {
            get {
                return ResourceManager.GetString("StationSettings13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notenleser manipuliert von {0} EUR auf {1}.
        /// </summary>
        internal static string StationSettings14 {
            get {
                return ResourceManager.GetString("StationSettings14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , Cash-Pool im Wert von:  {0} wurde gelöscht.
        /// </summary>
        internal static string StationSettings2 {
            get {
                return ResourceManager.GetString("StationSettings2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versuch, ungültigen CashPool-Wert zu lesen: {0}.
        /// </summary>
        internal static string StationSettings3 {
            get {
                return ResourceManager.GetString("StationSettings3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoher Cash-Pool-Wert gefunden: {0}.
        /// </summary>
        internal static string StationSettings5 {
            get {
                return ResourceManager.GetString("StationSettings5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to setCashInLimit: {0}.
        /// </summary>
        internal static string StationSettings6 {
            get {
                return ResourceManager.GetString("StationSettings6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception setting CashInLimit.
        /// </summary>
        internal static string StationSettings7 {
            get {
                return ResourceManager.GetString("StationSettings7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somebody tried to re-print a foreign ticket: {0}.
        /// </summary>
        internal static string StationSettings8 {
            get {
                return ResourceManager.GetString("StationSettings8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alte LiveBetOffset-Einstellung gefunden{0} {1}.
        /// </summary>
        internal static string StationSettings9 {
            get {
                return ResourceManager.GetString("StationSettings9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbekannter Match-Status am Terminal angezeigt {0}.
        /// </summary>
        internal static string TerminalMatchView1 {
            get {
                return ResourceManager.GetString("TerminalMatchView1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket erst beim 2. Mal erfolgreich an den Server gesendet..
        /// </summary>
        internal static string TicketHandler1 {
            get {
                return ResourceManager.GetString("TicketHandler1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket wurde nicht gespeichert. Einsatz: {0}.
        /// </summary>
        internal static string TicketHandler2 {
            get {
                return ResourceManager.GetString("TicketHandler2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote von Tip wurde nicht auf Station gefunden..
        /// </summary>
        internal static string TicketHandler3 {
            get {
                return ResourceManager.GetString("TicketHandler3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote von Tip wurde nicht auf Station gefunden..
        /// </summary>
        internal static string TicketHandler4 {
            get {
                return ResourceManager.GetString("TicketHandler4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Anzeigen der Live-Matches auf Bildschirm {0}: {1}.
        /// </summary>
        internal static string ViewControl1 {
            get {
                return ResourceManager.GetString("ViewControl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to show Table on terminal {0} Error: {1}.
        /// </summary>
        internal static string ViewControl2 {
            get {
                return ResourceManager.GetString("ViewControl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to show Ticket Details on terminal {0} Error: {1}.
        /// </summary>
        internal static string ViewControl3 {
            get {
                return ResourceManager.GetString("ViewControl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konnte Storno-Ticket nicht drucken mit Einsatz: {0}.
        /// </summary>
        internal static string ViewControl4 {
            get {
                return ResourceManager.GetString("ViewControl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storno-Ticket gedruckt mit Einsatz: {0}.
        /// </summary>
        internal static string ViewControl5 {
            get {
                return ResourceManager.GetString("ViewControl5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        internal static string ViewControl6 {
            get {
                return ResourceManager.GetString("ViewControl6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Aktualisieren der Quoten..
        /// </summary>
        internal static string ViewControl7 {
            get {
                return ResourceManager.GetString("ViewControl7", resourceCulture);
            }
        }
    }
}
